FROM robomap.azurecr.io/robomap-website:sec-web-20260724195053
COPY css/styles.css /usr/share/nginx/html/css/styles.css
COPY css/theme.css /usr/share/nginx/html/css/theme.css
COPY css/apple-theme.css /usr/share/nginx/html/css/apple-theme.css
