FROM robomap.azurecr.io/analytics-backend:36d91a93a88d013ef0a29babe248fd1ac2633ba4
COPY dist/api/auth/robomapSso.js /app/dist/api/auth/robomapSso.js
COPY dist/index.js /app/dist/index.js
COPY dist/cluster.js /app/dist/cluster.js
