FROM robomap.azurecr.io/robomap-backend:user-rating-20260724233736
COPY app/Support/FrontendUrl.php /var/www/html/app/Support/FrontendUrl.php
COPY app/Http/Controllers/Authentication/Auth/AuthenticateController.php /var/www/html/app/Http/Controllers/Authentication/Auth/AuthenticateController.php
COPY app/Http/Controllers/Authentication/Auth/FaceAuthenticationController.php /var/www/html/app/Http/Controllers/Authentication/Auth/FaceAuthenticationController.php
COPY app/Services/Web/WebCatalogService.php /var/www/html/app/Services/Web/WebCatalogService.php
COPY config/app_frontends.php /var/www/html/config/app_frontends.php
